[package]
name = "jrsx"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false
proc-macro = true

[dependencies]
quote = "1.0.35"
regex = "1.10.2"
syn = "2.0.48"

[dev-dependencies]
askama = "0.12.1"
